package com.ditadesigner.generator;

import com.ditadesigner.model.*;
import com.ditadesigner.transformer.ModelTransformer;
import com.ditadesigner.util.FileUtil;

import java.io.*;

/**
 * Generates an OASIS XML Catalog (catalog.xml) mapping public IDs and
 * system IDs to the generated DTD/XSD files.
 */
public class CatalogGenerator {

    private static final String NL = System.lineSeparator();
    private final ModelTransformer transformer = new ModelTransformer();

    public void generate(DitaModel model, File outputDir) throws IOException {
        String content = buildCatalog(model);
        FileUtil.writeString(new File(outputDir, "catalog.xml"), content);
    }

    private String buildCatalog(DitaModel model) {
        StringBuilder sb = new StringBuilder();

        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>").append(NL);
        sb.append("<!DOCTYPE catalog PUBLIC").append(NL);
        sb.append("    \"-//OASIS//DTD XML Catalogs V1.1//EN\"").append(NL);
        sb.append("    \"http://www.oasis-open.org/committees/entity/release/1.1/catalog.dtd\">").append(NL);
        sb.append(NL);
        sb.append("<!--").append(NL);
        sb.append("  XML Catalog for: ").append(model.getName()).append(NL);
        sb.append("  Generated by DITA Specialization Designer").append(NL);
        sb.append("-->").append(NL);
        sb.append(NL);
        sb.append("<catalog xmlns=\"urn:oasis:names:tc:entity:xmlns:xml:catalog\"").append(NL);
        sb.append("         prefer=\"public\">").append(NL).append(NL);

        // ── Topic types ───────────────────────────────────────────────
        if (!model.getTopicTypes().isEmpty()) {
            sb.append("  <!-- ═══════════════ Topic Type Modules ═══════════════ -->").append(NL);
            for (TopicType tt : model.getTopicTypes()) {
                String stem = tt.resolvedModule();
                String pubId = transformer.derivePublicId(tt, "LOCAL");
                String entPubId = pubId.replace("ELEMENTS", "ENTITIES");

                sb.append(NL);
                sb.append("  <!-- ").append(tt.getName()).append(" -->").append(NL);

                // .mod public ID
                sb.append("  <public publicId=\"").append(pubId).append("\"").append(NL);
                sb.append("          uri=\"dtd/").append(stem).append(".mod\"/>").append(NL);

                // .ent public ID
                sb.append("  <public publicId=\"").append(entPubId).append("\"").append(NL);
                sb.append("          uri=\"dtd/").append(stem).append(".ent\"/>").append(NL);

                // .dtd system ID
                sb.append("  <system systemId=\"").append(stem).append(".dtd\"").append(NL);
                sb.append("          uri=\"dtd/").append(stem).append(".dtd\"/>").append(NL);

                // XSD
                sb.append("  <uri name=\"").append(stem).append(".xsd\"").append(NL);
                sb.append("       uri=\"xsd/").append(stem).append(".xsd\"/>").append(NL);
            }
        }

        // ── Domains ───────────────────────────────────────────────────
        if (!model.getDomains().isEmpty()) {
            sb.append(NL);
            sb.append("  <!-- ═══════════════ Domain Modules ═══════════════════ -->").append(NL);
            for (DomainDef domain : model.getDomains()) {
                String dStem = domain.getName().toLowerCase();
                String dPubId = (domain.getPublicId() != null && !domain.getPublicId().isBlank())
                        ? domain.getPublicId()
                        : "-//LOCAL//ELEMENTS DITA " + domain.getName() + "//EN";
                sb.append(NL);
                sb.append("  <!-- ").append(domain.getName()).append(" domain -->").append(NL);
                sb.append("  <public publicId=\"").append(dPubId).append("\"").append(NL);
                sb.append("          uri=\"dtd/").append(dStem).append(".mod\"/>").append(NL);
            }
        }

        sb.append(NL);
        sb.append("</catalog>").append(NL);
        return sb.toString();
    }
}
