package com.ditadesigner.generator;

import com.ditadesigner.model.*;
import com.ditadesigner.transformer.ModelTransformer;
import com.ditadesigner.util.FileUtil;

import java.io.*;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates DITA DTD artefacts:
 * <ul>
 *   <li>{name}.dtd  — shell DTD</li>
 *   <li>{name}.mod  — element/attlist declarations</li>
 *   <li>{name}.ent  — entity declarations</li>
 * </ul>
 */
public class DtdGenerator {

    private static final String NL = System.lineSeparator();
    private final ModelTransformer transformer = new ModelTransformer();

    public void generate(DitaModel model, File outputDir) throws IOException {
        File dtdDir = new File(outputDir, "dtd");
        FileUtil.ensureDir(dtdDir);

        for (TopicType tt : model.getTopicTypes()) {
            generateForTopicType(tt, model, dtdDir);
        }
    }

    // ── per-topic-type generation ─────────────────────────────────────

    private void generateForTopicType(TopicType tt, DitaModel model, File dtdDir) throws IOException {
        String stem = tt.resolvedModule();

        FileUtil.writeString(new File(dtdDir, stem + ".ent"), buildEntFile(tt, model));
        FileUtil.writeString(new File(dtdDir, stem + ".mod"), buildModFile(tt, model));
        FileUtil.writeString(new File(dtdDir, stem + ".dtd"), buildDtdShell(tt, model));
    }

    // ── .ent file ─────────────────────────────────────────────────────

    private String buildEntFile(TopicType tt, DitaModel model) {
        StringBuilder sb = new StringBuilder();
        String stem = tt.resolvedModule();
        String pubId = transformer.derivePublicId(tt, "LOCAL");

        sb.append("<!-- =============================================================").append(NL);
        sb.append("     ").append(tt.getName()).append(" entity declarations").append(NL);
        sb.append("     Generated by DITA Specialization Designer").append(NL);
        sb.append("     ============================================================= -->").append(NL);
        sb.append(NL);

        // Domain string entity
        sb.append("<!ENTITY ").append(stem).append("-att").append(NL);
        sb.append("  \"(").append(stem).append(")\"").append(NL);
        sb.append(">").append(NL).append(NL);

        // Public ID entity for .mod file
        sb.append("<!ENTITY % ").append(stem).append("-typemod").append(NL);
        sb.append("  PUBLIC \"").append(pubId).append("\"").append(NL);
        sb.append("         \"").append(stem).append(".mod\"").append(NL);
        sb.append(">").append(NL);

        return sb.toString();
    }

    // ── .mod file ─────────────────────────────────────────────────────

    private String buildModFile(TopicType tt, DitaModel model) {
        StringBuilder sb = new StringBuilder();
        String stem = tt.resolvedModule();
        String base = tt.getBaseType();
        String classAttr = transformer.buildClassAttribute(tt);

        sb.append("<!-- =============================================================").append(NL);
        sb.append("     ").append(tt.getName()).append(" module").append(NL);
        sb.append("     Specializes from: ").append(base).append(NL);
        sb.append("     Generated by DITA Specialization Designer").append(NL);
        sb.append("     ============================================================= -->").append(NL);
        sb.append(NL);

        // ── parameter entities for element content models ─────────────
        sb.append("<!-- ============================================================= -->").append(NL);
        sb.append("<!--                    ELEMENT NAME ENTITIES                      -->").append(NL);
        sb.append("<!-- ============================================================= -->").append(NL).append(NL);

        sb.append("<!ENTITY % ").append(stem).append(" \"").append(stem).append("\">").append(NL).append(NL);

        // Per-element parameter entities
        for (ElementDef elem : tt.getElements()) {
            sb.append("<!ENTITY % ").append(elem.getName())
              .append(" \"").append(elem.getName()).append("\">").append(NL);
        }
        sb.append(NL);

        // ── content model parameter entities ─────────────────────────
        sb.append("<!-- ============================================================= -->").append(NL);
        sb.append("<!--                    CONTENT MODEL PARAMETERS                   -->").append(NL);
        sb.append("<!-- ============================================================= -->").append(NL).append(NL);

        // Top-level element content model
        String contentModel = buildTopicContentModel(tt);
        sb.append("<!ENTITY % ").append(stem).append(".content").append(NL);
        sb.append("  \"").append(contentModel).append("\"").append(NL);
        sb.append(">").append(NL).append(NL);

        // Top-level attlist entity
        sb.append("<!ENTITY % ").append(stem).append(".attributes").append(NL);
        sb.append("  \"").append(buildAttlistFragment(tt.getAttributes())).append("\"").append(NL);
        sb.append(">").append(NL).append(NL);

        // ── element declarations ──────────────────────────────────────
        sb.append("<!-- ============================================================= -->").append(NL);
        sb.append("<!--                    ELEMENT DECLARATIONS                       -->").append(NL);
        sb.append("<!-- ============================================================= -->").append(NL).append(NL);

        // Main topic type element
        sb.append("<!ELEMENT ").append(stem)
          .append(" %").append(stem).append(".content; >").append(NL);
        sb.append("<!ATTLIST ").append(stem).append(NL);
        sb.append("  %").append(stem).append(".attributes;").append(NL);
        sb.append("  class CDATA \"").append(classAttr).append("\"").append(NL);
        sb.append(">").append(NL).append(NL);

        // Child elements
        for (ElementDef elem : tt.getElements()) {
            String cm = (elem.getContentModel() != null && !elem.getContentModel().isBlank())
                    ? elem.getContentModel() : "(#PCDATA)*";
            sb.append("<!ELEMENT ").append(elem.getName()).append(" ").append(cm).append(" >").append(NL);
            if (!elem.getAttributes().isEmpty()) {
                sb.append("<!ATTLIST ").append(elem.getName()).append(NL);
                for (AttributeDef a : elem.getAttributes()) {
                    sb.append(a.toDtdFragment()).append(NL);
                }
                String elemClass = transformer.buildElementClassAttribute(tt, elem, null);
                sb.append("    class CDATA \"").append(elemClass).append("\"").append(NL);
                sb.append(">").append(NL);
            } else {
                String elemClass = transformer.buildElementClassAttribute(tt, elem, null);
                sb.append("<!ATTLIST ").append(elem.getName()).append(NL);
                sb.append("    class CDATA \"").append(elemClass).append("\"").append(NL);
                sb.append(">").append(NL);
            }
            sb.append(NL);
        }

        return sb.toString();
    }

    // ── .dtd shell ────────────────────────────────────────────────────

    private String buildDtdShell(TopicType tt, DitaModel model) {
        StringBuilder sb = new StringBuilder();
        String stem = tt.resolvedModule();
        String base = tt.getBaseType();
        String pubId = transformer.derivePublicId(tt, "LOCAL");

        sb.append("<!-- =============================================================").append(NL);
        sb.append("     ").append(tt.getName()).append(" DTD Shell").append(NL);
        sb.append("     Specializes from: ").append(base).append(NL);
        sb.append("     Public ID: ").append(pubId).append(NL);
        sb.append("     System ID: ").append(stem).append(".dtd").append(NL);
        sb.append("     Generated by DITA Specialization Designer").append(NL);
        sb.append("     ============================================================= -->").append(NL);
        sb.append(NL);

        // Include entity file
        sb.append("<!-- ============================================================= -->").append(NL);
        sb.append("<!--              TOPIC ENTITY DECLARATIONS                        -->").append(NL);
        sb.append("<!-- ============================================================= -->").append(NL).append(NL);

        sb.append("<!ENTITY % ").append(stem).append("-dec").append(NL);
        sb.append("  PUBLIC \"").append(pubId.replace("ELEMENTS", "ENTITIES")).append("\"").append(NL);
        sb.append("         \"").append(stem).append(".ent\"").append(NL);
        sb.append(">%").append(stem).append("-dec;").append(NL).append(NL);

        // Include base type module
        sb.append("<!-- ============================================================= -->").append(NL);
        sb.append("<!--              BASE TYPE MODULE                                 -->").append(NL);
        sb.append("<!-- ============================================================= -->").append(NL).append(NL);

        sb.append("<!ENTITY % ").append(base).append("-typemod").append(NL);
        sb.append("  PUBLIC \"-//OASIS//ELEMENTS DITA 1.3 ").append(capitalize(base)).append("//EN\"").append(NL);
        sb.append("         \"").append(base).append(".mod\"").append(NL);
        sb.append(">%").append(base).append("-typemod;").append(NL).append(NL);

        // Include this module
        sb.append("<!-- ============================================================= -->").append(NL);
        sb.append("<!--              SPECIALIZATION MODULE                            -->").append(NL);
        sb.append("<!-- ============================================================= -->").append(NL).append(NL);

        sb.append("%").append(stem).append("-typemod;").append(NL).append(NL);

        // Domain inclusions
        List<Relationship> domainRels = model.getRelationships().stream()
                .filter(r -> r.getType() == RelationshipType.DOMAIN_INCLUSION
                        && r.getTargetId().equals(tt.getId()))
                .collect(Collectors.toList());

        if (!domainRels.isEmpty()) {
            sb.append("<!-- ============================================================= -->").append(NL);
            sb.append("<!--              DOMAIN MODULES                                   -->").append(NL);
            sb.append("<!-- ============================================================= -->").append(NL).append(NL);

            for (Relationship rel : domainRels) {
                DomainDef domain = model.findDomainById(rel.getSourceId());
                if (domain != null) {
                    String dStem = domain.getName().toLowerCase();
                    sb.append("<!ENTITY % ").append(dStem).append("-dec").append(NL);
                    String dPubId = (domain.getPublicId() != null && !domain.getPublicId().isBlank())
                            ? domain.getPublicId()
                            : "-//LOCAL//ENTITIES DITA " + domain.getName() + "//EN";
                    sb.append("  PUBLIC \"").append(dPubId).append("\"").append(NL);
                    sb.append("         \"").append(dStem).append(".ent\"").append(NL);
                    sb.append(">%").append(dStem).append("-dec;").append(NL).append(NL);
                }
            }
        }

        return sb.toString();
    }

    // ── helper methods ────────────────────────────────────────────────

    private String buildTopicContentModel(TopicType tt) {
        if (tt.getElements().isEmpty()) {
            return "(title, shortdesc?, body?)";
        }
        StringBuilder cm = new StringBuilder("(");
        // Always include title
        cm.append("title");
        for (ElementDef elem : tt.getElements()) {
            cm.append(", ").append(elem.getName()).append(elem.cardinalitySuffix());
        }
        cm.append(")");
        return cm.toString();
    }

    private String buildAttlistFragment(List<AttributeDef> attrs) {
        if (attrs.isEmpty()) {
            return "id ID #REQUIRED";
        }
        StringBuilder sb = new StringBuilder();
        boolean hasId = attrs.stream().anyMatch(a -> "id".equalsIgnoreCase(a.getName()));
        if (!hasId) {
            sb.append("id ID #REQUIRED");
        }
        for (AttributeDef a : attrs) {
            if (sb.length() > 0) sb.append(NL).append("  ");
            sb.append(a.toDtdFragment().trim());
        }
        return sb.toString();
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }
}
