package com.ditadesigner.generator;

import com.ditadesigner.model.*;
import com.ditadesigner.transformer.ModelTransformer;
import com.ditadesigner.util.FileUtil;

import java.io.*;
import java.util.List;

/**
 * Generates W3C XML Schema (.xsd) artefacts for DITA specializations.
 * Uses xs:extension from the base DITA type.
 */
public class XsdGenerator {

    private static final String NL = System.lineSeparator();
    private static final String XS = "http://www.w3.org/2001/XMLSchema";
    private final ModelTransformer transformer = new ModelTransformer();

    public void generate(DitaModel model, File outputDir) throws IOException {
        File xsdDir = new File(outputDir, "xsd");
        FileUtil.ensureDir(xsdDir);

        for (TopicType tt : model.getTopicTypes()) {
            generateForTopicType(tt, model, xsdDir);
        }
    }

    private void generateForTopicType(TopicType tt, DitaModel model, File xsdDir) throws IOException {
        String stem = tt.resolvedModule();
        String content = buildXsd(tt, model);
        FileUtil.writeString(new File(xsdDir, stem + ".xsd"), content);
    }

    private String buildXsd(TopicType tt, DitaModel model) {
        StringBuilder sb = new StringBuilder();
        String stem = tt.resolvedModule();
        String base = tt.getBaseType();
        String ns = tt.getNamespace() != null ? tt.getNamespace() : "urn:ditadesigner:" + stem;
        String classAttr = transformer.buildClassAttribute(tt);

        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>").append(NL);
        sb.append("<!--").append(NL);
        sb.append("  ").append(tt.getName()).append(" XML Schema").append(NL);
        sb.append("  Specializes from: ").append(base).append(NL);
        sb.append("  Generated by DITA Specialization Designer").append(NL);
        sb.append("-->").append(NL);
        sb.append("<xs:schema").append(NL);
        sb.append("    xmlns:xs=\"").append(XS).append("\"").append(NL);
        sb.append("    xmlns:ditaarch=\"http://dita.oasis-open.org/architecture/2005/\"").append(NL);
        sb.append("    targetNamespace=\"").append(ns).append("\"").append(NL);
        sb.append("    xmlns=\"").append(ns).append("\"").append(NL);
        sb.append("    elementFormDefault=\"qualified\"").append(NL);
        sb.append("    attributeFormDefault=\"unqualified\">").append(NL).append(NL);

        // Import DITA base schema (reference only — user must supply actual base XSD)
        sb.append("  <!-- Import DITA base type schema -->").append(NL);
        sb.append("  <xs:import").append(NL);
        sb.append("      namespace=\"http://dita.oasis-open.org/architecture/2005/\"").append(NL);
        sb.append("      schemaLocation=\"").append(base).append(".xsd\"/>").append(NL).append(NL);

        // ── complex type via extension ────────────────────────────────
        sb.append("  <!-- ").append(tt.getName()).append(" complex type -->").append(NL);
        sb.append("  <xs:complexType name=\"").append(tt.getName()).append(".class\">").append(NL);
        sb.append("    <xs:complexContent>").append(NL);
        sb.append("      <xs:extension base=\"").append(base).append(".class\">").append(NL);

        if (!tt.getElements().isEmpty()) {
            sb.append("        <xs:sequence>").append(NL);
            // First: always allow title from base (omit re-declaration if it matches base)
            for (ElementDef elem : tt.getElements()) {
                sb.append(elementRef(elem));
            }
            sb.append("        </xs:sequence>").append(NL);
        }

        // Attributes
        sb.append("        <xs:attribute name=\"id\" type=\"xs:ID\" use=\"required\"/>").append(NL);
        sb.append("        <xs:attribute name=\"class\" type=\"xs:string\"").append(NL);
        sb.append("            default=\"").append(classAttr).append("\"/>").append(NL);
        for (AttributeDef attr : tt.getAttributes()) {
            sb.append(attributeDecl(attr));
        }
        sb.append("      </xs:extension>").append(NL);
        sb.append("    </xs:complexContent>").append(NL);
        sb.append("  </xs:complexType>").append(NL).append(NL);

        // ── element declaration ───────────────────────────────────────
        sb.append("  <!-- ").append(tt.getName()).append(" element declaration -->").append(NL);
        sb.append("  <xs:element name=\"").append(stem).append("\"").append(NL);
        sb.append("              type=\"").append(tt.getName()).append(".class\"/>").append(NL).append(NL);

        // ── child element complex types ───────────────────────────────
        for (ElementDef elem : tt.getElements()) {
            sb.append("  <!-- ").append(elem.getName()).append(" element -->").append(NL);
            sb.append("  <xs:element name=\"").append(elem.getName()).append("\">").append(NL);
            sb.append("    <xs:complexType mixed=\"true\">").append(NL);
            sb.append("      <xs:sequence minOccurs=\"0\" maxOccurs=\"unbounded\">").append(NL);
            sb.append("        <xs:any processContents=\"lax\" minOccurs=\"0\"/>").append(NL);
            sb.append("      </xs:sequence>").append(NL);
            for (AttributeDef a : elem.getAttributes()) {
                sb.append(attributeDecl(a));
            }
            String elemClass = transformer.buildElementClassAttribute(tt, elem, null);
            sb.append("      <xs:attribute name=\"class\" type=\"xs:string\" default=\"")
              .append(elemClass).append("\"/>").append(NL);
            sb.append("    </xs:complexType>").append(NL);
            sb.append("  </xs:element>").append(NL).append(NL);
        }

        sb.append("</xs:schema>").append(NL);
        return sb.toString();
    }

    private String elementRef(ElementDef elem) {
        String min = elem.isRequired() ? "1" : "0";
        String max = switch (elem.getCardinality()) {
            case "+", "*" -> "unbounded";
            default -> "1";
        };
        return "          <xs:element ref=\"" + elem.getName()
                + "\" minOccurs=\"" + min + "\" maxOccurs=\"" + max + "\"/>" + NL;
    }

    private String attributeDecl(AttributeDef attr) {
        StringBuilder sb = new StringBuilder();
        sb.append("        <xs:attribute name=\"").append(attr.getName()).append("\"");

        // Map DTD types to XSD types
        String xsType = switch (attr.getType()) {
            case "ID" -> "xs:ID";
            case "IDREF" -> "xs:IDREF";
            case "IDREFS" -> "xs:IDREFS";
            case "NMTOKEN" -> "xs:NMTOKEN";
            case "NMTOKENS" -> "xs:NMTOKENS";
            default -> "xs:string";
        };

        if (!attr.getEnumValues().isEmpty()) {
            sb.append(">").append(NL);
            sb.append("          <xs:simpleType><xs:restriction base=\"xs:string\">").append(NL);
            for (String val : attr.getEnumValues()) {
                sb.append("            <xs:enumeration value=\"").append(val).append("\"/>").append(NL);
            }
            sb.append("          </xs:restriction></xs:simpleType>").append(NL);
            sb.append("        </xs:attribute>").append(NL);
        } else {
            sb.append(" type=\"").append(xsType).append("\"");
            if (attr.isRequired()) sb.append(" use=\"required\"");
            else if (attr.getDefaultValue() != null && !attr.getDefaultValue().isBlank()) {
                sb.append(" default=\"").append(attr.getDefaultValue()).append("\"");
            }
            sb.append("/>").append(NL);
        }
        return sb.toString();
    }
}
