package com.ditadesigner.generator;

import com.ditadesigner.model.*;
import com.ditadesigner.transformer.ModelTransformer;
import com.ditadesigner.util.FileUtil;

import java.io.*;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Generates W3C XML Schema (.xsd) artefacts for DITA specializations.
 * Uses xs:extension from the base DITA type.
 */
public class XsdGenerator {

    private static final String NL = System.lineSeparator();
    private static final String XS = "http://www.w3.org/2001/XMLSchema";
    private final ModelTransformer transformer = new ModelTransformer();

    public void generate(DitaModel model, File outputDir) throws IOException {
        File xsdDir = new File(outputDir, "xsd");
        FileUtil.ensureDir(xsdDir);

        for (TopicType tt : model.getTopicTypes()) {
            generateForTopicType(tt, model, xsdDir);
        }
    }

    /** F-107: Returns the XSD content for a single TopicType without writing files. */
    public String previewXsd(TopicType tt, DitaModel model) {
        return buildCopyrightComment(model) + buildXsd(tt, model);
    }

    private void generateForTopicType(TopicType tt, DitaModel model, File xsdDir) throws IOException {
        String stem = tt.resolvedModule();
        String content = buildCopyrightComment(model) + buildXsd(tt, model);
        FileUtil.writeString(new File(xsdDir, stem + ".xsd"), content);
    }

    private String buildCopyrightComment(DitaModel model) {
        String owner = model.getCopyrightOwner();
        if (owner == null || owner.isBlank()) return "";
        int year = java.time.LocalDate.now().getYear();
        return "<!--" + NL
             + "  Copyright (c) " + year + " " + owner + NL
             + "  Project: " + model.getName() + " v" + (model.getVersion() != null ? model.getVersion() : "1.0") + NL
             + "  Generated by DITA Specialization Designer." + NL
             + "-->" + NL;
    }

    private String buildXsd(TopicType tt, DitaModel model) {
        StringBuilder sb = new StringBuilder();
        String stem = tt.resolvedModule();
        String base = tt.getBaseType();
        String ns = tt.getNamespace() != null ? tt.getNamespace() : "urn:ditadesigner:" + stem;
        String classAttr = transformer.buildClassAttribute(tt);

        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>").append(NL);
        sb.append("<!--").append(NL);
        sb.append("  ").append(tt.getName()).append(" XML Schema").append(NL);
        sb.append("  Specializes from: ").append(base).append(NL);
        sb.append("  Generated by DITA Specialization Designer").append(NL);
        sb.append("-->").append(NL);
        sb.append("<xs:schema").append(NL);
        sb.append("    xmlns:xs=\"").append(XS).append("\"").append(NL);
        sb.append("    xmlns:ditaarch=\"http://dita.oasis-open.org/architecture/2005/\"").append(NL);
        sb.append("    targetNamespace=\"").append(ns).append("\"").append(NL);
        sb.append("    xmlns=\"").append(ns).append("\"").append(NL);
        sb.append("    elementFormDefault=\"qualified\"").append(NL);
        sb.append("    attributeFormDefault=\"unqualified\">").append(NL).append(NL);

        // F-159 fix: reference the base schema by schemaLocation only (no incorrect namespace)
        sb.append("  <!-- Reference DITA base type schema (provide schemaLocation relative to your DITA-OT) -->").append(NL);
        sb.append("  <xs:import schemaLocation=\"").append(base).append(".xsd\"/>").append(NL).append(NL);

        // ── Identify top-level vs nested elements ─────────────────────
        // F-160 fix: only include elements in xs:sequence that are not referenced
        // inside another element's content model (those are nested elements).
        Set<String> referencedByOthers = buildReferencedByOthers(tt.getElements());
        List<ElementDef> topLevelElements = tt.getElements().stream()
                .filter(e -> e.getName() != null && !referencedByOthers.contains(e.getName()))
                .collect(Collectors.toList());

        // ── Separate regular vs attribute-domain attrs ────────────────
        // F-158 fix: exclude 'id' from regularAttrs since it's emitted separately below.
        List<AttributeDef> regularAttrs = tt.getAttributes().stream()
                .filter(a -> !a.isAttributeDomain() && !"id".equalsIgnoreCase(a.getName()))
                .collect(Collectors.toList());
        List<AttributeDef> domainAttrs  = tt.getAttributes().stream()
                .filter(AttributeDef::isAttributeDomain).collect(Collectors.toList());

        // ── complex type via extension ────────────────────────────────
        sb.append("  <!-- ").append(tt.getName()).append(" complex type -->").append(NL);
        sb.append("  <xs:complexType name=\"").append(tt.getName()).append(".class\">").append(NL);
        sb.append("    <xs:complexContent>").append(NL);
        sb.append("      <xs:extension base=\"").append(base).append(".class\">").append(NL);

        if (!topLevelElements.isEmpty()) {
            sb.append("        <xs:sequence>").append(NL);
            for (ElementDef elem : topLevelElements) {
                sb.append(elementRef(elem));
            }
            sb.append("        </xs:sequence>").append(NL);
        }

        // id attribute (always required for DITA topics)
        sb.append("        <xs:attribute name=\"id\" type=\"xs:ID\" use=\"required\"/>").append(NL);
        sb.append("        <xs:attribute name=\"class\" type=\"xs:string\"").append(NL);
        sb.append("            default=\"").append(classAttr).append("\"/>").append(NL);

        // Build domains value
        StringBuilder domainsVal = new StringBuilder("(").append(stem).append(")");
        for (AttributeDef a : domainAttrs) {
            domainsVal.append(" a(").append(a.getSpecializesFrom()).append(" ").append(a.getName()).append(")");
        }
        sb.append("        <xs:attribute name=\"domains\" type=\"xs:string\"").append(NL);
        sb.append("            default=\"").append(domainsVal).append("\"/>").append(NL);

        for (AttributeDef a : domainAttrs) {
            sb.append("        <xs:attributeGroup ref=\"").append(a.getName()).append("-d-attribute\"/>").append(NL);
        }
        for (AttributeDef attr : regularAttrs) {
            sb.append(attributeDecl(attr));
        }
        sb.append("      </xs:extension>").append(NL);
        sb.append("    </xs:complexContent>").append(NL);
        sb.append("  </xs:complexType>").append(NL).append(NL);

        // ── element declaration ───────────────────────────────────────
        sb.append("  <!-- ").append(tt.getName()).append(" element declaration -->").append(NL);
        sb.append("  <xs:element name=\"").append(stem).append("\"").append(NL);
        sb.append("              type=\"").append(tt.getName()).append(".class\"/>").append(NL).append(NL);

        // ── attribute domain attributeGroup declarations ─────────────
        Map<String, AttributeDef> allDomainAttrs = new LinkedHashMap<>();
        for (AttributeDef a : tt.getAttributes()) {
            if (a.isAttributeDomain()) allDomainAttrs.put(a.getName(), a);
        }
        for (ElementDef elem : tt.getElements()) {
            for (AttributeDef a : elem.getAttributes()) {
                if (a.isAttributeDomain()) allDomainAttrs.putIfAbsent(a.getName(), a);
            }
        }
        for (AttributeDef a : allDomainAttrs.values()) {
            sb.append("  <!--").append(NL);
            sb.append("    Attribute domain: @").append(a.getName()).append(NL);
            sb.append("    Specializes from: @").append(a.getSpecializesFrom()).append(NL);
            sb.append("  -->").append(NL);
            sb.append("  <xs:attributeGroup name=\"").append(a.getName()).append("-d-attribute\">").append(NL);
            sb.append("    <xs:annotation><xs:documentation>").append(NL);
            sb.append("      Attribute domain specializing from @").append(a.getSpecializesFrom()).append(".").append(NL);
            sb.append("    </xs:documentation></xs:annotation>").append(NL);
            String xsType = mapDtdTypeToXsd(a.getType());
            if (a.getEnumValues() != null && !a.getEnumValues().isEmpty()) {
                sb.append("    <xs:attribute name=\"").append(a.getName()).append("\">").append(NL);
                sb.append("      <xs:simpleType><xs:restriction base=\"xs:string\">").append(NL);
                for (String val : a.getEnumValues()) {
                    sb.append("        <xs:enumeration value=\"").append(val).append("\"/>").append(NL);
                }
                sb.append("      </xs:restriction></xs:simpleType>").append(NL);
                sb.append("    </xs:attribute>").append(NL);
            } else {
                sb.append("    <xs:attribute name=\"").append(a.getName()).append("\"");
                sb.append(" type=\"").append(xsType).append("\"");
                if (a.isRequired()) sb.append(" use=\"required\"");
                else if (a.getDefaultValue() != null && !a.getDefaultValue().isBlank())
                    sb.append(" default=\"").append(a.getDefaultValue()).append("\"");
                sb.append("/>").append(NL);
            }
            sb.append("  </xs:attributeGroup>").append(NL).append(NL);
        }

        // ── child element complex types ───────────────────────────────
        // F-162 fix: track declared element names to avoid duplicate global declarations.
        Set<String> declaredElemNames = new LinkedHashSet<>();
        for (ElementDef elem : tt.getElements()) {
            if (!declaredElemNames.add(elem.getName())) {
                continue; // skip duplicate
            }
            sb.append("  <!-- ").append(elem.getName()).append(" element -->").append(NL);
            sb.append("  <xs:element name=\"").append(elem.getName()).append("\">").append(NL);
            sb.append("    <xs:complexType mixed=\"true\">").append(NL);
            sb.append("      <xs:sequence minOccurs=\"0\" maxOccurs=\"unbounded\">").append(NL);
            sb.append("        <xs:any processContents=\"lax\" minOccurs=\"0\"/>").append(NL);
            sb.append("      </xs:sequence>").append(NL);
            for (AttributeDef a : elem.getAttributes()) {
                if (a.isAttributeDomain()) {
                    sb.append("      <xs:attributeGroup ref=\"").append(a.getName()).append("-d-attribute\"/>").append(NL);
                } else {
                    sb.append(attributeDecl(a));
                }
            }
            String elemClass = transformer.buildElementClassAttribute(tt, elem, null);
            sb.append("      <xs:attribute name=\"class\" type=\"xs:string\" default=\"")
              .append(elemClass).append("\"/>").append(NL);
            sb.append("    </xs:complexType>").append(NL);
            sb.append("  </xs:element>").append(NL).append(NL);
        }

        sb.append("</xs:schema>").append(NL);
        return sb.toString();
    }

    /**
     * F-160 fix: build the set of element names that are referenced inside
     * any sibling element's content model string (i.e., they are "nested"
     * elements that should NOT appear in the parent topic's xs:sequence).
     */
    private Set<String> buildReferencedByOthers(List<ElementDef> elems) {
        Set<String> referenced = new HashSet<>();
        for (ElementDef elem : elems) {
            String cm = elem.getContentModel();
            if (cm == null || cm.isBlank()) continue;
            for (ElementDef other : elems) {
                if (!other.equals(elem) && other.getName() != null
                        && cm.contains(other.getName())) {
                    referenced.add(other.getName());
                }
            }
        }
        return referenced;
    }

    private String elementRef(ElementDef elem) {
        String min = elem.isRequired() ? "1" : "0";
        String max = switch (elem.getCardinality()) {
            case "+", "*" -> "unbounded";
            default -> "1";
        };
        return "          <xs:element ref=\"" + elem.getName()
                + "\" minOccurs=\"" + min + "\" maxOccurs=\"" + max + "\"/>" + NL;
    }

    private String attributeDecl(AttributeDef attr) {
        StringBuilder sb = new StringBuilder();
        String type = attr.getType() != null ? attr.getType() : "CDATA";
        sb.append("        <xs:attribute name=\"").append(attr.getName()).append("\"");

        // F-161 fix: detect DTD-style inline enum syntax (val1|val2|...) in the type field
        List<String> enumVals = attr.getEnumValues();
        if (enumVals == null || enumVals.isEmpty()) {
            enumVals = parseDtdEnumType(type);
        }

        if (!enumVals.isEmpty()) {
            sb.append(">").append(NL);
            sb.append("          <xs:simpleType><xs:restriction base=\"xs:string\">").append(NL);
            for (String val : enumVals) {
                sb.append("            <xs:enumeration value=\"").append(val).append("\"/>").append(NL);
            }
            sb.append("          </xs:restriction></xs:simpleType>").append(NL);
            sb.append("        </xs:attribute>").append(NL);
        } else {
            String xsType = mapDtdTypeToXsd(type);
            sb.append(" type=\"").append(xsType).append("\"");
            if (attr.isRequired()) sb.append(" use=\"required\"");
            else if (attr.getDefaultValue() != null && !attr.getDefaultValue().isBlank()) {
                sb.append(" default=\"").append(attr.getDefaultValue()).append("\"");
            }
            sb.append("/>").append(NL);
        }
        return sb.toString();
    }

    /** Map DTD attribute types to XSD built-in types. */
    private String mapDtdTypeToXsd(String dtdType) {
        if (dtdType == null) return "xs:string";
        return switch (dtdType) {
            case "ID"       -> "xs:ID";
            case "IDREF"    -> "xs:IDREF";
            case "IDREFS"   -> "xs:IDREFS";
            case "NMTOKEN"  -> "xs:NMTOKEN";
            case "NMTOKENS" -> "xs:NMTOKENS";
            default         -> "xs:string";
        };
    }

    /**
     * F-161 fix: parse DTD inline enum syntax "(val1|val2|val3)" from the type
     * field and return the list of values. Returns empty list if not an enum type.
     */
    private List<String> parseDtdEnumType(String type) {
        if (type == null || !type.startsWith("(") || !type.endsWith(")") || !type.contains("|")) {
            return List.of();
        }
        String inner = type.substring(1, type.length() - 1);
        return Arrays.stream(inner.split("\\|"))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .collect(Collectors.toList());
    }
}
